name: Daily Threads Post

on:
  schedule:
    # 매일 오후 1시에 실행 (UTC 기준)
    - cron: '0 4 * * *'  # 한국 시간 오후 1시 = UTC 4시
  workflow_dispatch:  # 수동 실행 옵션 추가

jobs:
  post-to-threads:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Thread Generator
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        THREADS_ACCESS_TOKEN: ${{ secrets.THREADS_ACCESS_TOKEN }}
      run: python thread_generator.py 